###
### Available Directives:
###     IncludeConfigs: Path to another config files to include
###                     Config files at the top of this list override settings in those below it
###     Zones: Zones to be defined, these can also be used in FirewallRules (see below)
###     UnsafeZones: These zones will be excluded from certain zone-type comparsion, see below for details
###     ZonePolicy:
###         FilterSelfOutbound: Should 'Self' (IE. The router itself) be filtered on outbound traffic
###         Interfaces: Mapping of interfaces to zones
###             {Zone}: Zone name to add an interface to
###                 - ethX: Adding an interface to a zone
###     AddressGroups: Define address groups which can be used in firewall rules or NAT's
###         * See AddressGroup documentation for further details
###     NetworkGroups: Define network groups which can be used in firewall rules or NAT's
###         * See NetworkGroup documentation for further details
###     PortGroups: Define port groups which can be used in firewall rules or NAT's
###         * See PortGroup documentation for further details
###     RuleTemplates: Defines rules which can be used in firewall zones
###         * See RuleTemplates documentation for further details
###     FirewallRules: Add rules to zones
###         ALL_ZONES: Add rules to all zone-pairs
###         SAFE_ZONES: Add rule to zones-pairs where neither zone is in the UnsafeZone list
###         UNSAFE_ZONES: Add rules to zone-pairs originating or destined from a zone in the UnsafeZone list
###         {Zone}: Add rules to zone-pairs where {Zone} is either the source or detination zone
###         TO_{Zone}: Add rules to zone-pairs where the destinate zone is {Zone} (excluding zone-pairs where the Source zone is in the UnsafeZone list)
###         FROM_{Zone}: Add rules to zone-pairs where the source zone is {Zone} (excluding zone-pairs where the destination zone is in the UnsafeZone list)
###         {ZonePair}: Add rules to a specific zone-pair (Eg. Servers-To-External)
###     NATRules: Defines NAT rules
###         * See NATRule documenetation for further details
###

