###
### Generic configuration file
### All directives can be overridden in either the per-host or additional configuration files
###
### Available Directives:
###     IncludeConfigs: Path to other config files to include, their settings override the Generic config
###     Zones: Zones to be defined
###     RestrictedZones: These zones will not inherit rules added to the UNRESTRICTED_ZONES list
###     ZonePolicy:
###         FilterSelfOutbound: Should 'Self' (IE. The router itself) be filtered on outbound traffic
###         Interfaces: Mapping of interfaces to zones
###     AddressGroups: Define address groups which can be used in firewall rules or NAT's
###     NetworkGroups: Define network groups which can be used in firewall rules or NAT's
###     PortGroups: Define port groups which can be used in firewall rules or NAT's
###     RuleTemplates: Defines rules which can be used in firewall zones
###     FirewallRules: Add rules to zones
###         ALL_ZONES: These rules get added to all zones, including restricted zones
###         UNRESTRICTED_ZONES: These rules get added to all zones except those in the RestrictedZones list
###         {ZonePair}: Add rules to a specific zone pair. Eg.  Servers-To-External
###     NATRules: Defines NAT rules
###

IncludeConfigs:
    - examples/example_included_config.yaml

Zones:
    - External
    - DMZ
    - Servers

RestrictedZones:
    - External
    - DMZ

ZonePolicy:
    FilterSelfOutbound: False
    Interfaces:
        External:
            - eth0
        Servers:
            - eth1
        DMZ:
            - eth2

AddressGroups:
    TrustedHost:
        - 8.8.8.8

NetworkGroups:
    TrustedNetwork:
        - 8.0.0.0/8

NetworkGroups:
    RFC1918:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

PortGroups:
    TrustedPorts:
        - 8
        - 88

RuleTemplates:
    DROP_ICMP:
        number: 55
        description: Drop ICMP
        log: enable
        action: drop
        protocol: icmp

    ALLOW_RFC1918_SSH:
        number: 64
        action: accept
        protocol: tcp
        description: Allow SSH from RFC1918
        source:
            - group network-group RFC1918
        destination:
            - group network-group RFC1918
            - port 22

    ALLOW_TRUSTED_TRAFFIC:
        description: Allows trusted traffic
        number: 100
        action: accept
        protocol: tcp_udp
        log: ''
        source:
            - address 0.0.0.0/0
        destination:
            - group address-group TrustedHost
            - group port-group TrustedPorts

FirewallRules:
    ALL_ZONES:
        - DROP_ICMP

    UNRESTRICTED_ZONES:
        - ALLOW_RFC1918_SSH
        
    Servers-To-External:
        - ALLOW_TRUSTED_TRAFFIC

NATRules:
    source:
        1:
            description: S-NAT Everything
            outbound-interface: any
            protocol: tcp_udp
            translation: 1.2.3.4
            source:
                - address 172.19.0.0/24
                - port 8,88
            destination:
                - address 0.0.0.0/0

    destination:
        100:
            description: D-NAT Everything
            inbound-interface: any
            protocol: tcp_udp
            translation: 172.234.0.10
            source:
                - address 0.0.0.0
            destination:
                - address 1.2.3.4
                - port 8,88

