###
### Per-host configuration file
### Directives here override those specified in the template and generic configuration files
### Use this to define rules which only exist on this specific firewall.
### Example: NAT rules for an IP that only exist on this router
###
### Available Directives::
###     * All directives available in the generic configuration file
###     role: Firewall template to include
###

role: config/roles/london/edge-router.yaml

RuleTemplates:
    PerHostRule:
        description: Allows trusted traffic
        number: 120
        action: accept
        protocol: tcp_udp
